"""
Django settings for relevamiento project.

Generated by 'django-admin startproject' using Django 3.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
import django_heroku
import dj_database_url
from decouple import config 


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-v5h7yw)70rdq!$6u116hqavf@zwmy7wjv5vg%8_+xlm3mw6tmk'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

LOGIN_REDIRECT_URL = 'index'   #'index'
LOGOUT_REDIRECT_URL = 'index'  #'index'


INSTALLED_APPS = [ #aplicaciones instaladas del proyecto si se crea una nueva aplicación se debe instalar desde aca
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'farmacia',
    'mathfilters',
    'crispy_forms',
]

CRISPY_TEMPLATE_PACK = 'bootstrap4'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'relevamiento.urls' #ruta donde se encuentra el archivo que maneja las rutas del proyecto

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'relevamiento.wsgi.application'


# Database

# https://docs.djangoproject.com/en/3.2/ref/settings/#databases


# https://auth-db176.hostinger.com/index.php?db=u551789018_relevamiento
# BASE: u551789018_relevamiento 
# user: u551789018_agus_fer 
# Pass: Chizzo1991 
# host:185.201.11.212

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql', 
        'NAME': 'u551789018_relevamiento',
        'USER': 'u551789018_agus_fer',
        'PASSWORD': 'Chizzo1991',
        'HOST': '185.201.11.212',   
        'PORT': '3306',
    }    
}




# altgraph==0.17
# asgiref==3.3.4
# dj-database-url==0.5.0
# Django==3.2.3
# django-crispy-forms==1.12.0
# django-heroku==0.3.1
# django-mathfilters==1.0.0
# django-widget-tweaks==1.4.8
# future==0.18.2
# gunicorn==20.1.0
# mysql-connector-python==8.0.24
# mysqlclient==2.0.3
# pefile==2021.5.24
# Pillow==8.3.1
# plumbum==1.7.0
# protobuf==3.15.8
# psutil==5.8.0
# psycopg2==2.9.1
# pyinstaller==4.3
# pyinstaller-hooks-contrib==2021.1
# PyMySQL==1.0.2
# pypiwin32==223
# python-decouple==3.4
# pytz==2021.1
# pywin32==300
# pywin32-ctypes==0.2.0
# six==1.16.0
# sqlparse==0.4.1
# whitenoise==5.3.0
# winapps==0.2.0



# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'es-ar'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

#STATIC_URL = '/static/'

STATIC_URL = '/static/' # URL para referenciar a la carpeta static

STATICFILES_DIRS = [os.path.join(BASE_DIR,'static'),] # en esta lista se le indica a django donde esta la carpeta static en el sistema

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


django_heroku.settings(locals())