# Generated by Django 3.2.5 on 2021-07-21 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmacia',
            fields=[
                ('fica_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre Fcia')),
                ('direccion', models.CharField(max_length=50, verbose_name='Dirección')),
            ],
            options={
                'verbose_name': 'Farmacia',
                'verbose_name_plural': 'Farmacias',
            },
        ),
        migrations.CreateModel(
            name='Fcia',
            fields=[
                ('id_farmacia', models.IntegerField(primary_key=True, serialize=False, verbose_name='id_farmacia')),
                ('nombre_facia', models.CharField(max_length=256, verbose_name='nombre_farmacia')),
                ('direccion', models.CharField(max_length=256, verbose_name='direccion')),
                ('ip', models.CharField(blank=True, default='192.168.0.', max_length=256, null=True)),
            ],
            options={
                'verbose_name': 'Fcia',
                'verbose_name_plural': 'Fcias',
            },
        ),
        migrations.CreateModel(
            name='Pc_Farmacia',
            fields=[
                ('fecha_relevamiento', models.DateField(blank=True, null=True, verbose_name='Fecha-Relevamiento')),
                ('ip', models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name='IP')),
                ('nombre_pc', models.CharField(blank=True, max_length=256, null=True, verbose_name='nombre_pc')),
                ('ip_publica', models.CharField(blank=True, max_length=256, null=True, verbose_name='ip_publica')),
                ('arquitectura_so', models.CharField(blank=True, max_length=256, null=True, verbose_name='arquitectura_so')),
                ('version_so', models.CharField(blank=True, max_length=50, null=True, verbose_name='version')),
                ('tipo_maquina', models.CharField(blank=True, max_length=256, null=True, verbose_name='tipo_maquina')),
                ('procesador', models.CharField(blank=True, max_length=256, null=True, verbose_name='procesador')),
                ('cores_fisicos', models.IntegerField(blank=True, null=True, verbose_name='cores_fisicos')),
                ('cores_totales', models.IntegerField(blank=True, null=True, verbose_name='cores_totales')),
                ('RAM_tot', models.CharField(blank=True, max_length=256, null=True, verbose_name='ram_total')),
                ('RAM_usada', models.CharField(blank=True, max_length=256, null=True, verbose_name='ram_usada')),
                ('RAM_disponible', models.CharField(blank=True, max_length=256, null=True, verbose_name='ram_disponible')),
                ('RAM_procentaje_disponible', models.CharField(blank=True, max_length=256, null=True, verbose_name='RAM_disponible')),
                ('espacio_tot_C', models.CharField(blank=True, max_length=256, null=True, verbose_name='espacio_total_C')),
                ('espacio_tot_D', models.CharField(blank=True, max_length=256, null=True, verbose_name='espacio_total_D')),
                ('espacio_usado_C', models.CharField(blank=True, max_length=256, null=True, verbose_name='espacio_usado_C')),
                ('espacio_usado_D', models.CharField(blank=True, max_length=256, null=True, verbose_name='espacio_usado_D')),
                ('espacio_disponible_C', models.CharField(blank=True, max_length=256, null=True, verbose_name='espacio_disponible_C')),
                ('espacio_disponible_D', models.CharField(blank=True, max_length=256, null=True, verbose_name='espacio_disponible_D')),
                ('procentaje_disponible_C', models.CharField(blank=True, max_length=256, null=True, verbose_name='porcentaje_disponible_C')),
                ('procentaje_disponible_D', models.CharField(blank=True, max_length=256, null=True, verbose_name='porcentaje_disponible_D')),
                ('AnyDesk_instalado', models.CharField(blank=True, max_length=256, null=True, verbose_name='any_instalado')),
                ('id_AnyDesk', models.CharField(blank=True, max_length=256, null=True, verbose_name='any_instalado')),
                ('farmacia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farmacia.fcia')),
            ],
            options={
                'verbose_name': 'computadora',
                'verbose_name_plural': 'computadoras',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id_perfil', models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name='id_perfil')),
                ('descripcion', models.CharField(max_length=256, verbose_name='descripción perfil')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('programa', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Programa')),
                ('version', models.CharField(blank=True, max_length=100, verbose_name='Nombre del Programa')),
                ('fecha_install', models.DateField()),
                ('estado', models.IntegerField(choices=[(0, 'Desactivar'), (1, 'Activar')], default=1)),
            ],
            options={
                'verbose_name': 'Programa',
                'verbose_name_plural': 'Programas',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id_provincia', models.IntegerField(primary_key=True, serialize=False, verbose_name='id_provincia')),
                ('descripcion', models.CharField(max_length=256, verbose_name='descripcion')),
                ('estado', models.IntegerField(choices=[(0, 'Desactivar'), (1, 'activar')], default=1)),
            ],
            options={
                'verbose_name': 'provincia',
                'verbose_name_plural': 'provincias',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name='id_usuario')),
                ('nombre', models.CharField(max_length=256, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=256, verbose_name='apellido')),
                ('usuario', models.CharField(max_length=256, verbose_name='usuario')),
                ('baja', models.BooleanField(default=True, verbose_name='usuario dado de baja si/no')),
                ('id_perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmacia.perfil')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Programas_instalados',
            fields=[
                ('programa_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Programa')),
                ('version', models.CharField(blank=True, max_length=100, verbose_name='Nombre del Programa')),
                ('fecha_rel', models.DateField(blank=True, null=True, verbose_name='Fecha-Relevamiento')),
                ('fecha_install', models.CharField(max_length=256, verbose_name='Fecha de isntalación')),
                ('pc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farmacia.pc_farmacia')),
            ],
            options={
                'verbose_name': 'Programa_pc',
                'verbose_name_plural': 'Programas_pc',
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id_localidad', models.IntegerField(primary_key=True, serialize=False, verbose_name='id_localidad')),
                ('descripcion', models.CharField(max_length=256, verbose_name='descripcion')),
                ('estado', models.IntegerField(choices=[(1, 'Activar'), (0, 'Desactivar')], default=1)),
                ('id_provincia_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmacia.provincia')),
            ],
            options={
                'verbose_name': 'localidad',
                'verbose_name_plural': 'localidades',
            },
        ),
        migrations.AddField(
            model_name='fcia',
            name='id_localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmacia.localidad'),
        ),
        migrations.CreateModel(
            name='Cantidad_Programas',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(verbose_name='cantidad de programas')),
                ('tabla_programas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farmacia.programas_instalados')),
            ],
            options={
                'verbose_name': 'cantidad_programas',
            },
        ),
    ]
